In [128]:
import records
from pyecharts import Pie, Bar, Page

db = records.Database('mysql://root:root@39.108.141.110:3306/Jobs')

#### 1. 饼图

In [134]:
def show_pie(db, sql, title='Pie'):
    rows = db.query(sql)
    df = rows.export('df')
    columns = df.columns.tolist()
    labels, datas = df[columns[0]], df[columns[1]]
    pie = Pie(title)
    pie.add('总数:{sum}'.format(sum=sum(datas)), labels, datas, is_label_show=True)
    return pie
    
sql = "select type, count(*) as count from jobanalysis where type !='' group by type"
show_pie(db, sql)

#### 2. 环形图

In [135]:
def show_pie2(db, sql, title='Pie'):
    rows = db.query(sql)
    df = rows.export('df')
    columns = df.columns.tolist()
    out_labels, counts = df[columns[1]], df[columns[2]]
    
    inner_data = {}
    for key, item in df.groupby(columns[0]):
        inner_data[key] = item[columns[2]].sum()
        
    pie = Pie(title)
    pie.add('', inner_data.keys(), inner_data.values(), radius=[0, 30], legend_orient='vertical', legend_pos='left')
    pie.add('', out_labels, counts, radius=[40, 53], is_label_show=True)

    return pie

sql = "select type, concat(type,'_',edu), count(2) as count from jobanalysis where type in ('Python', '数据挖掘') and edu!='不限' group by type, edu"
show_pie2(db, sql, title='Pie')

#### 3. 柱状图

In [136]:
def show_bar(db, sql, title='Bar'):
    rows = db.query(sql)
    df = rows.export('df')
    columns = df.columns.tolist()
    row, col = df.shape
    bar = Bar(title)
    
    if col == 2:
        labels, counts = df[columns[0]], df[columns[1]]
        bar.add('', labels, counts, mark_point=["max", "min"])
    
    elif col == 3:
        labels = list(set(df[columns[1]]))
        for key, item in df.groupby(columns[0]):
            dct = dict(zip(item[columns[1]], item[columns[2]]))
            data = [dct.get(label, 0) for label in labels]
            bar.add(key, labels, data, mark_point=["max", "min"])
            
    return bar

page = Page()
sql = "select type, count(*) as count from jobanalysis where type !='' group by type"
page.add(show_bar(db, sql, 'Bar1'))

sql = "select * from (select type, address, count(*) as count from jobanalysis where type in ('Python', 'Java', '数据挖掘') group by type, address) temp where temp.count > 100"
page.add(show_bar(db, sql, 'Bar2'))

page

In [158]:
from pyecharts import WordCloud

name = ['Sam S Club', 'Macys', 'Amy Schumer', 'Jurassic World', 'Charter Communications',
        'Chick Fil A', 'Planet Fitness', 'Pitch Perfect', 'Express', 'Home', 'Johnny Depp',
        'Lena Dunham', 'Lewis Hamilton', 'KXAN', 'Mary Ellen Mark', 'Farrah Abraham',
        'Rita Ora', 'Serena Williams', 'NCAA baseball tournament', 'Point Break']
value = [10000, 6181, 4386, 4055, 2467, 2244, 1898, 1484, 1112, 965, 847, 582, 555,
         550, 462, 366, 360, 282, 273, 265]
wordcloud = WordCloud(width=1300, height=620)
wordcloud.add("", name, value, word_size_range=[20, 100])

print(wordcloud.render_embed())

<div id="0a1041532b944964a2d098f2cabb3eae" style="width:1300px;height:620px;"></div>
<script type="text/javascript">
    var myChart_0a1041532b944964a2d098f2cabb3eae = echarts.init(document.getElementById('0a1041532b944964a2d098f2cabb3eae'));
    var option_0a1041532b944964a2d098f2cabb3eae = {
    "title": [
        {
            "text": "",
            "subtext": "",
            "left": "auto",
            "top": "auto",
            "textStyle": {
                "color": "#000",
                "fontSize": 18
            },
            "subtextStyle": {
                "color": "#aaa",
                "fontSize": 12
            }
        }
    ],
    "toolbox": {
        "show": true,
        "orient": "vertical",
        "left": "95%",
        "top": "center",
        "feature": {
            "saveAsImage": {
                "show": true,
                "title": "\u4e0b\u8f7d\u56fe\u7247"
            },
            "restore": {
                "show": true
            },
            "dataView": {
                "show": true
            }
        }
    },
    "series_id": 6757556,
    "tooltip": {},
    "series": [
        {
            "type": "wordCloud",
            "name": "",
            "shape": "circle",
            "rotationRange": [
                -90,
                90
            ],
            "rotationStep": 45,
            "girdSize": 20,
            "sizeRange": [
                20,
                100
            ],
            "data": [
                {
                    "name": "Sam S Club",
                    "value": 10000,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(58,34,148)"
                        }
                    }
                },
                {
                    "name": "Macys",
                    "value": 6181,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(5,94,15)"
                        }
                    }
                },
                {
                    "name": "Amy Schumer",
                    "value": 4386,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(158,103,8)"
                        }
                    }
                },
                {
                    "name": "Jurassic World",
                    "value": 4055,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(54,78,78)"
                        }
                    }
                },
                {
                    "name": "Charter Communications",
                    "value": 2467,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(79,26,151)"
                        }
                    }
                },
                {
                    "name": "Chick Fil A",
                    "value": 2244,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(157,77,21)"
                        }
                    }
                },
                {
                    "name": "Planet Fitness",
                    "value": 1898,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(2,93,22)"
                        }
                    }
                },
                {
                    "name": "Pitch Perfect",
                    "value": 1484,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(78,119,20)"
                        }
                    }
                },
                {
                    "name": "Express",
                    "value": 1112,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(109,110,79)"
                        }
                    }
                },
                {
                    "name": "Home",
                    "value": 965,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(27,69,102)"
                        }
                    }
                },
                {
                    "name": "Johnny Depp",
                    "value": 847,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(100,15,13)"
                        }
                    }
                },
                {
                    "name": "Lena Dunham",
                    "value": 582,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(48,68,156)"
                        }
                    }
                },
                {
                    "name": "Lewis Hamilton",
                    "value": 555,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(117,150,89)"
                        }
                    }
                },
                {
                    "name": "KXAN",
                    "value": 550,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(49,78,103)"
                        }
                    }
                },
                {
                    "name": "Mary Ellen Mark",
                    "value": 462,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(151,17,120)"
                        }
                    }
                },
                {
                    "name": "Farrah Abraham",
                    "value": 366,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(99,139,81)"
                        }
                    }
                },
                {
                    "name": "Rita Ora",
                    "value": 360,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(103,130,150)"
                        }
                    }
                },
                {
                    "name": "Serena Williams",
                    "value": 282,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(111,156,17)"
                        }
                    }
                },
                {
                    "name": "NCAA baseball tournament",
                    "value": 273,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(118,20,98)"
                        }
                    }
                },
                {
                    "name": "Point Break",
                    "value": 265,
                    "textStyle": {
                        "normal": {
                            "color": "rgb(9,159,122)"
                        }
                    }
                }
            ]
        }
    ],
    "legend": [
        {
            "data": []
        }
    ],
    "backgroundColor": "#fff"
};
    myChart_0a1041532b944964a2d098f2cabb3eae.setOption(option_0a1041532b944964a2d098f2cabb3eae);
</script>